### ISSUE TITLE
Use Result on binary predicates (to handle possible GEOS exception)

### ISSUE THREAD

**Issue by mthh** [georust/rust-geos#10]
In order to expose a safe interface and to not alter the results returned by GEOS I guess we should check the value returned by the various [binary predicates](https://github.com/OSGeo/geos/blob/master/capi/geos_c.h.in#L1668) and wrap it in a `Result`.
GEOS is returning 2 for an exception (that we could transform to an `Err`) or 1/0 if its true/false (that we could wrap in a `Ok`).
Currently we are doing like this : https://github.com/georust/rust-geos/blob/master/src/ffi.rs#L464

If no one is already working on it I will send a PR today, sorry this error remained in the code so long of my fault!

**Comment by antoine-de** [comment]
oops you're right, nice catch!

don't forget to bump the minor version number as it will break the API (but in a good way :wink: )
